### PR TITLE
Add opensuse patches

### PR DESCRIPTION
**Pull request by dcermak**
Submission of openSUSE specific patches in the hopes that they are useful on non-openSUSE distributions, too.

### CODE REVIEW

**Comment by petdance** [comment]
Please tell me more about this patch.  I wouldn't think an RPM would be searchable.

**Comment by dcermak** [comment]
> Please tell me more about this patch. 

These patches existed for quite some time in the opensuse `ack` package. I've helped the current maintainer updating ack and thought I'd submit them (or drop them otherwise).

> I wouldn't think an RPM would be searchable.

No, a RPM is not really searchable, but the "recipe" for building a RPM is. RPMs are build from plain text spec-files, which are added by this patch.

The ignored directory `.osc` is created by openSUSE's tool `osc` and can generally be ignored when searching, as it contains internal information to build a RPM from a spec file.

**Comment by petdance** [comment]
So what is `osc`?  I don't know anything about openSUSE.

>  thought I'd submit them (or drop them otherwise).

I'm not sure what you mean here.  Why would you drop them?  I assume by "drop" you mean no longer have them in the ack package for openSUSE.

I definitely don't want to call something `--rpm` that doesn't actually deal with RPM files, assuming we're talking about the RPM packages that are used for Linux packaging.

**Comment by dcermak** [comment]
"Andy Lester" <notifications@github.com> writes:

> So what is `osc`?  I don't know anything about openSUSE.

`osc` is a utility program to communicate with the Open Build Service, a
server for building packages for various Linux Distributions (mostly
used to build openSUSE on https://build.opensuse.org/).

`osc` also supports local builds, where it creates a `.osc` directory
which it fills with downloaded build time dependencies and other "junk"
that you don't really want to search through.

>
>>  thought I'd submit them (or drop them otherwise).
>
> I'm not sure what you mean here.  Why would you drop them?  I assume by "drop" you mean no longer have them in the ack package for openSUSE.
>

I am trying to follow a strict "upstream first" policy: if upstream
doesn't want to maintain a patch and it is not absolutely crucial for my
OS, then it must be dropped. Otherwise one can easily end up with a ton
of custom patches, that become a huge maintenance burden.

> I definitely don't want to call something `--rpm` that doesn't actually deal with RPM files, assuming we're talking about the RPM packages that are used for Linux packaging. 
>

How about changing the name to `--spec` then? spec files kind of deal
with RPM files, but only indirectly.

**Comment by dcermak** [comment]
@petdance Any update on this? Would you prefer anything being changed in this PR?

**Comment by petdance** [comment]
I'm not sure that I want to add it, especially if the openSUSE package already excludes it.  The more I add, the more of a maintenance hassle it is.

**Comment by dcermak** [comment]
That's a pity, since the author of the patches is no longer maintaining the package and the current maintainer had trouble keeping the patches up to date.

**Comment by petdance** [comment]
I understand, and it also shines a light on why I'm reluctant to add it.  It's hard to keep track of every file type that gets added to ack, and adding customizations that only a few people know about makes it even worse.

I'm curious, however, as to what patches that the package maintainer was adding.  Adding a single directory exclusion to a single source file in ack doesn't seem like it would be a big change, so I'm wondering if there are other things in there as well.

**Comment by dcermak** [comment]
> I'm curious, however, as to what patches that the package maintainer was adding. Adding a single directory exclusion to a single source file in ack doesn't seem like it would be a big change, so I'm wondering if there are other things in there as well. Maybe I can help simplify the Suse-specific patches.

The above patches are all there is. The "issue" with these patches is that the current openSUSE maintainer has very little coding experience and is "just" a ack user, who took the package so that it doesn't get deleted. I've tried to upstream these patches, so that he doesn't have to do that anymore. So I don't think you can simplify these anymore.

**Comment by andreasstieger** [comment]
Hi there. I can add some context for one of the patches:

`.osc`: This is a essentially a local working tree format an version control system for rpm maintenance. Similar to `.git`, `.svn` and similarly implemented systems. It has a local cache and thus duplicated findings. Excluding this should be straightforward.

**Comment by petdance** [comment]
> The patch is only useful for users of osc, which is primarily openSUSE and users of the Open Build Service.

Understood.  That's why I've decided not to include it.

**Comment by carlwgeorge** [comment]
> I understand, and it also shines a light on why I'm reluctant to add it. It's hard to keep track of every file type that gets added to ack, and adding customizations that only a few people know about makes it even worse.

That's understandable.  It's probably more than a "few people" that would benefit from the OpenSUSE-specific stuff, but it is still a somewhat limited audience.

That said, I think the RPM spec file type would have a bit more impact.  It's used across many popular distributions.  Would the project be open to including a default type for RPM spec files?  I agree that a type of `rpm` doesn't make sense, but I think that `spec` or `rpmspec` would.  If so then I'm happy to send a pull request to add it, I just figured I would ask here first.

**Comment by petdance** [comment]
> That said, I think the RPM spec file type would have a bit more impact.

It might, but I haven't heard any requests for it.

My approach on adding filetypes to ack is that I add things that people have 1) requested and 2) used for a while in their .ackrc files. I don't go looking for filetypes that could possibly get used, since they're a [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) without someone wanting them.

**Comment by carlwgeorge** [comment]
I imagine with openSUSE carrying [this patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/ack/ack-add_spec.patch) you won't see any requests for this from their packager maintainers.  I work on Fedora and am considering adding a similar patch there, but for now I'm content to just carry this in my local `.ackrc`.  I'll keep an ear out to see if other Fedora maintainers see this as useful.

**Pull request closed without merging**
