### PR TITLE
Adds isolated docker development environment

### PR DESCRIPTION
**Pull request by mscottford**
Adds support for spinning up a development environment that runs in an isolated Docker container.

I've been running an experiment the last year or so where I keep my base system clean and only do development inside of Docker containers. I'm contributing the `docker-compose`-based setup that I created so I can contribute to this project.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the PR.  I'm trying to understand why someone would run ack inside of a container.

**Comment by mscottford** [comment]
This is just working on ack. Not for running ack. This allows me to have an isolated perl installation for working on ack. I'm sure there are other ways to achieve that, and I also suspect they would require I install dev tools directly on my development workstation.

**Comment by mscottford** [comment]
I tried to write up some [documentation](https://github.com/beyondgrep/ack3/pull/208/files#diff-710af9c85139525b79a31decd9f92c91R91) to describe how this could be used.

**Comment by n1vux** [comment]
> This is just working on ack. Not for running ack. This allows me to have an isolated perl installation for working on ack. I'm sure there are other ways 

Having sandboxes for development is useful!  Docker is particularly useful when developing _servers_; and it's lighter weight than a full VM; but it's still overkill for developing commandline tools. OTOH, having a standard dev environment isn't _per se_ a bad thing.

FWIW, I use Perlbrew and Perlbrew's wrapper for Local Lib - a local lib with just `File::Next`, or `Class::Std`, depending which module I'm working on, as well as default with only the fresh-out-of-box lib and another "loaded" lib with all my favorites.  This avoids touching the system perl and avoids a single $HOME perllib spoiling your development will older versions of thing under dev on the paths. With Travis &c, it's less necessary for me to test with multiple Perl versions on my system, but Perlbrew makes replicating an issue with a specific Perl build practical. This is much lighter separation than Docker -- which is sometimes a feature, i can compare code in multiple Git clones without tunneling into mulitple dockers -- but still lets me develop with just the minimal prereqs for the current project when that's desirable.

Having hints on how to make a Docker dev env in the `DEVELOPERS.md` file is good for anyone else taking this angle on sandboxed development.  

I don't know that we need to publish the Docker recipe/scripts for a Ack dev sandbox.  OTOH, if we make sure it looks optional, it's harmless.  In that light, I'd suggest they be relocated into the `./dev/`  tooling directory, maybe even `./dev/docker/` ?

**Comment by mscottford** [comment]
> FWIW, I use Perlbrew and Perlbrew's wrapper for Local Lib - a local lib with just File::Next, or Class::Std, depending which module I'm working on, as well as default with only the fresh-out-of-box lib and another "loaded" lib with all my favorites. This avoids touching the system perl and avoids a single $HOME perllib spoiling your development will older versions of thing under dev on the paths. 

I suspected there was a way to go about doing that. I'm very familiar with `rbenv` and `pyenv`, which provide similar setups for `ruby` and `python` respectively. But I was trying to avoid installing anything else on my local workstation. That's the approach I've been taking with all my development of late.

> In that light, I'd suggest they be relocated into the ./dev/ tooling directory, maybe even ./dev/docker/ ?

I'm happy to move it into there and update the docker-related files and documentation to reflect that location.

**Comment by mscottford** [comment]
Docker-related files now live in the `dev/docker` directory and the documentation has been updated with the correct command to run it from there.

**Comment by petdance** [comment]
I'll try to look at this tonight or tomorrow.  I'm still not clear why you'd want to have a docker container for doing dev, but I also haven't looked at the docs you wrote up yet.

**Pull request merged**
