### PR TITLE
Fix error in output when `-x` is used with `-s`

### PR DESCRIPTION
**Pull request by mscottford**
Attempts to fix issue #175. Suppress file missing output when `-x` is used in combination with `-s`.

Includes commits from pull request #208, but those can be removed via rebase if needed.

### CODE REVIEW

**Comment by mscottford** [comment]
I remove the test that I wrote for this. I realized after the fact that I had overlooked the one written by @petdance.

**Comment by mscottford** [comment]
This fix was developed during the Hackathon session at The Perl Conference in Pittsburg 2019 (TPCiP 2019).

**Comment by n1vux** [comment]
*Thank you* for doing `ack` at the Hackathon !  

(Wish I was there ... but I've got a client deadline and a different event next weekend ... )

**Comment by petdance** [comment]
Thanks.  I've incorporated these changes into the fix at 93d50b8f64736268ce361805ba42ece835fa9d66.

**Pull request closed without merging**
