### PR TITLE
Skip build_regex() with --line for STDIN, just like for files

### PR DESCRIPTION
**Pull request by timgimyee**
For #146.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this.  We are probably going to get rid of --lines entirely anyway.  See #167.  This fix and the bug that it reminds us of just adds to my thinking that we should get rid of it.

**Comment by n1vux** [comment]
OTOH if we do a final close-the-door release with final bugfixes & doc fixes on Ack2, patch'ing the diff to Ack 2 may be worthwhile to leave it in good final state (code matching docs).

**Comment by petdance** [comment]
Good point.  Will you please make a corresponding ticket in ack2 that refers back to this one?

**Comment by petdance** [comment]
Thanks for this PR.  I'm closing this as I've just now removed the `--lines` option entirely'

**Pull request closed without merging**
